version: '3.7'

services:
  #Products Web Api
  serverproducts:
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    ports:
      - "80:80"
    
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data